sonar.projectKey=Insaner1980_runcheck
sonar.organization=insaner1980

sonar.sources=app/src/main/java
sonar.java.binaries=app/build/intermediates/javac/debug/classes,app/build/tmp/kotlin-classes/debug

# Exclude generated files from all analysis
sonar.exclusions=**/build/**,**/generated/**,**/*Generated*.kt

# Exclude generated files from duplication analysis
sonar.cpd.exclusions=**/build/**,**/generated/**

# Exclude generated files from coverage analysis
sonar.coverage.exclusions=**/build/**,**/generated/**
