name: Qodana Main

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  checks: write

jobs:
  qodana:
    name: Qodana Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Qodana Scan
        uses: JetBrains/qodana-action@4861e015da555e86a72b862892aba6c2b93e6891 # v2026.1.3
        with:
          primary-cache-key: qodana-main-2026.1-${{ github.ref }}-${{ github.sha }}
          additional-cache-key: qodana-main-2026.1-${{ github.ref }}
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN_773626803 }}
