name: Qodana Main

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  checks: write

jobs:
  qodana:
    name: Qodana Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Qodana Scan
        uses: JetBrains/qodana-action@3e8d76ff0e0241618abd808682f426afe84bab3f # v2026.2.2
        with:
          primary-cache-key: qodana-main-2026.2-${{ github.ref }}-${{ github.sha }}
          additional-cache-key: qodana-main-2026.2-${{ github.ref }}
