name: Qodana

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  checks: write

jobs:
  qodana:
    name: Qodana Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Qodana Scan
        uses: JetBrains/qodana-action@f5aa2889b113c16bd6aee47817b027537ee33ac7 # v2025.1
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
